export const CustomColors = {
  light: {
    primary: '#261c39',
    onPrimary: '#261c39',
    secondary: '#03fa96',
    background: '#ffffff',
    onBackground: '#556a',
    surface: '#ddd',
    error: '#e04040',
    text: '#000000',
    placeholder: '#aaa',
    secondaryContainer: '#261c39',
    onSecondaryContainer: '#fff',
    onSurface: '#888',
    onSurfaceVariant: '#dee',
    onSurfaceDisabled: '#eee',
    tertiary: '#ffabd3',
    tertiaryContainer: '#fea9a6',
    onTertiaryContainer: '#ffc1aa',
  },
  dark: {
    primary: '#328ba3',
    onPrimary: '#fff',
    secondary: '#03fa96',
    background: '#261c39',
    onBackground: '#328ba3',
    surface: '#261c39',
    error: '#e04040',
    text: '#ffffff',
    placeholder: '#bbb',
    secondaryContainer: '#328ba3',
    onSecondaryContainer: '#fff',
    onSurface: '#328ba3',
    onSurfaceVariant: '#22294f',
    onSurfaceDisabled: '#1e3561',
    tertiary: '#fb7bb3',
    tertiaryContainer: '#fb93a3',
    onTertiaryContainer: '#f9a19a',
  },
};
